LineItem extra field for FulfillmentOrder usage
chewlim/shopify-php-sdk pull request #3
Opened 2022-09-16 03:02 UTC by h2akim

- Fix formatting
- Add LineItem additional fields that is used by FulfillmentOrder service response
- add `onlyReturnedData()` method to only get returned data (by key)

2022-09-19 00:28 UTC, chewlim commented on src/Enum/Fields/LineItemFields.php
> +    const line_item_id = 'line_item_id';
Please changed the const to upper case

2022-09-19 00:29 UTC, chewlim requested changes
@h2akim see comment

2022-09-19 00:41 UTC, h2akim commented on src/Enum/Fields/LineItemFields.php
> +    const line_item_id = 'line_item_id';
updated

2022-09-20 11:33 UTC, chewlim approved these changes

2022-09-20 11:33 UTC, merged